// Command dataobj-flight serves Loki data objects from a local directory over
// Arrow Flight so that external query engines, such as DataFusion through
// tools/dataobj-sql, can run SQL against them. With -archive-dir it also
// serves an archive_logs table from gzipped OTLP JSON archive objects.
//
// Example, using the data generated by `make generate` in pkg/logql/bench:
//
//	go run ./tools/dataobj-flight -dir pkg/logql/bench/data/storage/dataobj \
//	    -archive-dir pkg/logql/bench/data/archive -archive-tenant test-tenant
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"strings"
	"syscall"

	"github.com/apache/arrow-go/v18/arrow/flight"
	"github.com/go-kit/log"
	"github.com/go-kit/log/level"
	"github.com/thanos-io/objstore/providers/filesystem"

	"github.com/grafana/loki/v3/pkg/dataobj/arrowflight"
)

func main() {
	var (
		dir     = flag.String("dir", "pkg/logql/bench/data/storage/dataobj", "Root directory of the data object bucket.")
		prefix  = flag.String("prefix", "objects", "Prefix within the bucket under which data objects are discovered.")
		addr    = flag.String("addr", "127.0.0.1:8815", "Address to listen on.")
		verbose = flag.Bool("v", false, "Enable debug logging.")

		archiveDir      = flag.String("archive-dir", "", "Root directory of an archive bucket (gzipped OTLP JSON under <tenant>/YYYY/MM/DD/HH/mm/). Enables the archive_logs table.")
		archiveTenant   = flag.String("archive-tenant", "", "Tenant directory within -archive-dir.")
		archiveLabels   = flag.String("archive-labels", "", "Comma-separated OTLP resource attributes promoted to stream labels for native OTLP objects. Defaults to Loki's default list.")
		archiveColumns  = flag.String("archive-label-columns", "", "Comma-separated label columns of archive_logs. Discovered from the first objects when empty.")
		archiveMetadata = flag.String("archive-metadata", strings.Join(arrowflight.DefaultArchiveMetadataColumns, ","), "Comma-separated structured metadata keys exposed as columns of archive_logs (the rest is in log_attributes).")
	)
	flag.Parse()

	logger := log.NewLogfmtLogger(log.NewSyncWriter(os.Stderr))
	if *verbose {
		logger = level.NewFilter(logger, level.AllowDebug())
	} else {
		logger = level.NewFilter(logger, level.AllowInfo())
	}

	archive := archiveOptions{
		dir:          *archiveDir,
		tenant:       *archiveTenant,
		labels:       splitList(*archiveLabels),
		labelColumns: splitList(*archiveColumns),
		metadata:     splitList(*archiveMetadata),
	}
	if err := run(context.Background(), *dir, *prefix, *addr, archive, logger); err != nil {
		level.Error(logger).Log("msg", "dataobj-flight failed", "err", err)
		os.Exit(1)
	}
}

type archiveOptions struct {
	dir, tenant  string
	labels       []string
	labelColumns []string
	metadata     []string
}

func splitList(s string) []string {
	var out []string
	for _, part := range strings.Split(s, ",") {
		if part = strings.TrimSpace(part); part != "" {
			out = append(out, part)
		}
	}
	return out
}

func run(ctx context.Context, dir, prefix, addr string, archive archiveOptions, logger log.Logger) error {
	bucket, err := filesystem.NewBucket(dir)
	if err != nil {
		return fmt.Errorf("opening bucket at %s: %w", dir, err)
	}

	catalog, err := arrowflight.OpenCatalog(ctx, bucket, prefix, logger)
	if err != nil {
		return fmt.Errorf("opening catalog: %w", err)
	}

	for _, name := range catalog.Tables() {
		ts, _ := catalog.Table(name)
		parts, _ := catalog.Partitions(name)
		level.Info(logger).Log("msg", "serving table", "table", name, "columns", ts.Schema.NumFields(), "partitions", len(parts))
		for _, f := range ts.Schema.Fields() {
			level.Debug(logger).Log("table", name, "column", f.Name, "type", f.Type)
		}
	}

	sources := []arrowflight.Source{catalog}
	if archive.dir != "" {
		archiveBucket, err := filesystem.NewBucket(archive.dir)
		if err != nil {
			return fmt.Errorf("opening archive bucket at %s: %w", archive.dir, err)
		}
		src, err := arrowflight.NewArchiveSource(ctx, arrowflight.ArchiveConfig{
			Bucket:          archiveBucket,
			Prefix:          archive.tenant,
			IndexLabels:     archive.labels,
			LabelColumns:    archive.labelColumns,
			MetadataColumns: archive.metadata,
			Logger:          logger,
		})
		if err != nil {
			return fmt.Errorf("opening archive: %w", err)
		}
		ts, _ := src.Table(arrowflight.TableArchiveLogs)
		level.Info(logger).Log("msg", "serving table", "table", arrowflight.TableArchiveLogs, "columns", ts.Schema.NumFields(), "dir", archive.dir, "tenant", archive.tenant)
		for _, f := range ts.Schema.Fields() {
			level.Debug(logger).Log("table", arrowflight.TableArchiveLogs, "column", f.Name, "type", f.Type)
		}
		sources = append(sources, src)
	}

	srv := flight.NewServerWithMiddleware(nil)
	if err := srv.Init(addr); err != nil {
		return fmt.Errorf("listening on %s: %w", addr, err)
	}
	srv.RegisterFlightService(arrowflight.NewServer(logger, sources...))
	srv.SetShutdownOnSignals(os.Interrupt, syscall.SIGTERM)

	level.Info(logger).Log("msg", "dataobj-flight listening", "addr", srv.Addr().String())
	return srv.Serve()
}
