// Command dataobj-flight serves Loki data objects from a local directory over
// Arrow Flight so that external query engines, such as DataFusion through
// tools/dataobj-sql, can run SQL against them.
//
// Example, using the data generated by `make generate` in pkg/logql/bench:
//
//	go run ./tools/dataobj-flight -dir pkg/logql/bench/data/storage/dataobj
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"syscall"

	"github.com/apache/arrow-go/v18/arrow/flight"
	"github.com/go-kit/log"
	"github.com/go-kit/log/level"
	"github.com/thanos-io/objstore/providers/filesystem"

	"github.com/grafana/loki/v3/pkg/dataobj/arrowflight"
)

func main() {
	var (
		dir     = flag.String("dir", "pkg/logql/bench/data/storage/dataobj", "Root directory of the data object bucket.")
		prefix  = flag.String("prefix", "objects", "Prefix within the bucket under which data objects are discovered.")
		addr    = flag.String("addr", "127.0.0.1:8815", "Address to listen on.")
		verbose = flag.Bool("v", false, "Enable debug logging.")
	)
	flag.Parse()

	logger := log.NewLogfmtLogger(log.NewSyncWriter(os.Stderr))
	if *verbose {
		logger = level.NewFilter(logger, level.AllowDebug())
	} else {
		logger = level.NewFilter(logger, level.AllowInfo())
	}

	if err := run(context.Background(), *dir, *prefix, *addr, logger); err != nil {
		level.Error(logger).Log("msg", "dataobj-flight failed", "err", err)
		os.Exit(1)
	}
}

func run(ctx context.Context, dir, prefix, addr string, logger log.Logger) error {
	bucket, err := filesystem.NewBucket(dir)
	if err != nil {
		return fmt.Errorf("opening bucket at %s: %w", dir, err)
	}

	catalog, err := arrowflight.OpenCatalog(ctx, bucket, prefix, logger)
	if err != nil {
		return fmt.Errorf("opening catalog: %w", err)
	}

	for _, name := range catalog.Tables() {
		ts, _ := catalog.Table(name)
		parts, _ := catalog.Partitions(name)
		level.Info(logger).Log("msg", "serving table", "table", name, "columns", ts.Schema.NumFields(), "partitions", len(parts))
		for _, f := range ts.Schema.Fields() {
			level.Debug(logger).Log("table", name, "column", f.Name, "type", f.Type)
		}
	}

	srv := flight.NewServerWithMiddleware(nil)
	if err := srv.Init(addr); err != nil {
		return fmt.Errorf("listening on %s: %w", addr, err)
	}
	srv.RegisterFlightService(arrowflight.NewServer(catalog, logger))
	srv.SetShutdownOnSignals(os.Interrupt, syscall.SIGTERM)

	level.Info(logger).Log("msg", "dataobj-flight listening", "addr", srv.Addr().String())
	return srv.Serve()
}
