// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: scan.proto

// Package loki.dataobj.scan.v1 defines the messages exchanged between a
// DataFusion (or any Arrow Flight) client and the Loki data object Flight
// server. The client plans a scan by sending a ScanRequest as a Flight
// descriptor command; the server answers with one Flight endpoint per data
// object section, each carrying a Ticket that the client redeems with DoGet.

package scanpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Op is the comparison applied by a Predicate.
type Op int32

const (
	Op_OP_UNSPECIFIED Op = 0
	Op_OP_EQ          Op = 1
	Op_OP_IN          Op = 2
	Op_OP_GT          Op = 3
	Op_OP_GTE         Op = 4
	Op_OP_LT          Op = 5
	Op_OP_LTE         Op = 6
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "OP_EQ",
		2: "OP_IN",
		3: "OP_GT",
		4: "OP_GTE",
		5: "OP_LT",
		6: "OP_LTE",
	}
	Op_value = map[string]int32{
		"OP_UNSPECIFIED": 0,
		"OP_EQ":          1,
		"OP_IN":          2,
		"OP_GT":          3,
		"OP_GTE":         4,
		"OP_LT":          5,
		"OP_LTE":         6,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_scan_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_scan_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{0}
}

// ScanRequest describes a projection and a conjunction of predicates over a
// table exposed by the server.
type ScanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the table to scan: "logs" or "streams".
	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// Columns to return, in order. Empty returns every column of the table.
	Columns []string `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	// Predicates that every returned row must satisfy. Predicates are a hint:
	// the server prunes what it can and may return rows that do not match, so
	// clients must re-apply the filters.
	Predicates []*Predicate `protobuf:"bytes,3,rep,name=predicates,proto3" json:"predicates,omitempty"`
	// Maximum number of rows the client needs. Zero means unlimited. Servers may
	// ignore this.
	Limit         int64 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ScanRequest) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ScanRequest) GetPredicates() []*Predicate {
	if x != nil {
		return x.Predicates
	}
	return nil
}

func (x *ScanRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Literal is a constant value compared against a column.
type Literal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Literal_StringValue
	//	*Literal_Int64Value
	//	*Literal_Uint64Value
	//	*Literal_TimestampNs
	//	*Literal_BytesValue
	Value         isLiteral_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Literal) Reset() {
	*x = Literal{}
	mi := &file_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Literal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Literal) ProtoMessage() {}

func (x *Literal) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Literal.ProtoReflect.Descriptor instead.
func (*Literal) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{1}
}

func (x *Literal) GetValue() isLiteral_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Literal) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Literal_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Literal) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*Literal_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *Literal) GetUint64Value() uint64 {
	if x != nil {
		if x, ok := x.Value.(*Literal_Uint64Value); ok {
			return x.Uint64Value
		}
	}
	return 0
}

func (x *Literal) GetTimestampNs() int64 {
	if x != nil {
		if x, ok := x.Value.(*Literal_TimestampNs); ok {
			return x.TimestampNs
		}
	}
	return 0
}

func (x *Literal) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Literal_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isLiteral_Value interface {
	isLiteral_Value()
}

type Literal_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Literal_Int64Value struct {
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Literal_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,3,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type Literal_TimestampNs struct {
	// Nanoseconds since the Unix epoch, UTC.
	TimestampNs int64 `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs,proto3,oneof"`
}

type Literal_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*Literal_StringValue) isLiteral_Value() {}

func (*Literal_Int64Value) isLiteral_Value() {}

func (*Literal_Uint64Value) isLiteral_Value() {}

func (*Literal_TimestampNs) isLiteral_Value() {}

func (*Literal_BytesValue) isLiteral_Value() {}

// Predicate compares a single column against one (comparison ops) or many
// (OP_IN) literals.
type Predicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Op            Op                     `protobuf:"varint,2,opt,name=op,proto3,enum=loki.dataobj.scan.v1.Op" json:"op,omitempty"`
	Values        []*Literal             `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Predicate) Reset() {
	*x = Predicate{}
	mi := &file_scan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Predicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Predicate) ProtoMessage() {}

func (x *Predicate) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Predicate.ProtoReflect.Descriptor instead.
func (*Predicate) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{2}
}

func (x *Predicate) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *Predicate) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_OP_UNSPECIFIED
}

func (x *Predicate) GetValues() []*Literal {
	if x != nil {
		return x.Values
	}
	return nil
}

// Ticket identifies one unit of work for DoGet: a section of a data object,
// scanned with the given request.
type Ticket struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Request *ScanRequest           `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	// Path of the data object within the server's bucket.
	ObjectPath string `protobuf:"bytes,2,opt,name=object_path,json=objectPath,proto3" json:"object_path,omitempty"`
	// Index of the section within the data object.
	SectionIndex  int32 `protobuf:"varint,3,opt,name=section_index,json=sectionIndex,proto3" json:"section_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_scan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{3}
}

func (x *Ticket) GetRequest() *ScanRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Ticket) GetObjectPath() string {
	if x != nil {
		return x.ObjectPath
	}
	return ""
}

func (x *Ticket) GetSectionIndex() int32 {
	if x != nil {
		return x.SectionIndex
	}
	return 0
}

var File_scan_proto protoreflect.FileDescriptor

const file_scan_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"scan.proto\x12\x14loki.dataobj.scan.v1\"\x94\x01\n" +
	"\vScanRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12?\n" +
	"\n" +
	"predicates\x18\x03 \x03(\v2\x1f.loki.dataobj.scan.v1.PredicateR\n" +
	"predicates\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\"\xc7\x01\n" +
	"\aLiteral\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vint64_value\x18\x02 \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fuint64_value\x18\x03 \x01(\x04H\x00R\vuint64Value\x12#\n" +
	"\ftimestamp_ns\x18\x04 \x01(\x03H\x00R\vtimestampNs\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"\x84\x01\n" +
	"\tPredicate\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12(\n" +
	"\x02op\x18\x02 \x01(\x0e2\x18.loki.dataobj.scan.v1.OpR\x02op\x125\n" +
	"\x06values\x18\x03 \x03(\v2\x1d.loki.dataobj.scan.v1.LiteralR\x06values\"\x8b\x01\n" +
	"\x06Ticket\x12;\n" +
	"\arequest\x18\x01 \x01(\v2!.loki.dataobj.scan.v1.ScanRequestR\arequest\x12\x1f\n" +
	"\vobject_path\x18\x02 \x01(\tR\n" +
	"objectPath\x12#\n" +
	"\rsection_index\x18\x03 \x01(\x05R\fsectionIndex*\\\n" +
	"\x02Op\x12\x12\n" +
	"\x0eOP_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05OP_EQ\x10\x01\x12\t\n" +
	"\x05OP_IN\x10\x02\x12\t\n" +
	"\x05OP_GT\x10\x03\x12\n" +
	"\n" +
	"\x06OP_GTE\x10\x04\x12\t\n" +
	"\x05OP_LT\x10\x05\x12\n" +
	"\n" +
	"\x06OP_LTE\x10\x06B;Z9github.com/grafana/loki/v3/pkg/dataobj/arrowflight/scanpbb\x06proto3"

var (
	file_scan_proto_rawDescOnce sync.Once
	file_scan_proto_rawDescData []byte
)

func file_scan_proto_rawDescGZIP() []byte {
	file_scan_proto_rawDescOnce.Do(func() {
		file_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scan_proto_rawDesc), len(file_scan_proto_rawDesc)))
	})
	return file_scan_proto_rawDescData
}

var file_scan_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scan_proto_goTypes = []any{
	(Op)(0),             // 0: loki.dataobj.scan.v1.Op
	(*ScanRequest)(nil), // 1: loki.dataobj.scan.v1.ScanRequest
	(*Literal)(nil),     // 2: loki.dataobj.scan.v1.Literal
	(*Predicate)(nil),   // 3: loki.dataobj.scan.v1.Predicate
	(*Ticket)(nil),      // 4: loki.dataobj.scan.v1.Ticket
}
var file_scan_proto_depIdxs = []int32{
	3, // 0: loki.dataobj.scan.v1.ScanRequest.predicates:type_name -> loki.dataobj.scan.v1.Predicate
	0, // 1: loki.dataobj.scan.v1.Predicate.op:type_name -> loki.dataobj.scan.v1.Op
	2, // 2: loki.dataobj.scan.v1.Predicate.values:type_name -> loki.dataobj.scan.v1.Literal
	1, // 3: loki.dataobj.scan.v1.Ticket.request:type_name -> loki.dataobj.scan.v1.ScanRequest
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_scan_proto_init() }
func file_scan_proto_init() {
	if File_scan_proto != nil {
		return
	}
	file_scan_proto_msgTypes[1].OneofWrappers = []any{
		(*Literal_StringValue)(nil),
		(*Literal_Int64Value)(nil),
		(*Literal_Uint64Value)(nil),
		(*Literal_TimestampNs)(nil),
		(*Literal_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scan_proto_rawDesc), len(file_scan_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scan_proto_goTypes,
		DependencyIndexes: file_scan_proto_depIdxs,
		EnumInfos:         file_scan_proto_enumTypes,
		MessageInfos:      file_scan_proto_msgTypes,
	}.Build()
	File_scan_proto = out.File
	file_scan_proto_goTypes = nil
	file_scan_proto_depIdxs = nil
}
